@hostname = localhost
@port = 3333
@host = http://{{hostname}}:{{port}}

@emailSportsman = user@notfound2.local
@emailCoach = user@notfound3.local
@password = 123456

@authTokenCoach = {{loginCoach.response.body.accessToken}}
@authTokenSportsman = {{loginSportsman.response.body.accessToken}}
# Login coach
# @name loginCoach
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailCoach}}",
  "password": "{{password}}"
}

###
# Login sportsman
# @name loginSportsman
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailSportsman}}",
  "password": "{{password}}"
}

###

# Get all users
GET {{host}}/api/users HTTP/1.1
Authorization: Bearer {{authTokenSportsman}}

###

# Get user 
GET http://localhost:3333/api/users/c733fe4-712d-4adb-848c-51d22fd035e1 HTTP/1.1
Authorization: Bearer {{authTokenSportsman}}

###

# Update user
PATCH http://localhost:3333/api/users/update HTTP/1.1
Authorization: Bearer {{authTokenSportsman}}
Content-Type: application/json

{
  "avatar": "user2.png",
  "gender": "Женский"
}

###
