@hostname = localhost
@port = 3333
@host = http://{{hostname}}:{{port}}

@emailSportsman = user@notfound2.local
@emailCoach = user@notfound3.local
@password = 123456

@authTokenCoach = {{loginCoach.response.body.accessToken}}
@authTokenSportsman = {{loginSportsman.response.body.accessToken}}
# Login coach
# @name loginCoach
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailCoach}}",
  "password": "{{password}}"
}

###
# Login sportsman
# @name loginSportsman
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailSportsman}}",
  "password": "{{password}}"
}

###

# Create a new purchase
POST {{host}}/api/purchases/bef656a4-9eaf-41ad-b12d-64d37a834e73 HTTP/1.1
Authorization: Bearer {{authTokenCoach}}
Content-Type: application/json

{
  "purchaseType": "тренировка",
  "countExercise": 3,
  "paymentMethod": "visa"
}

###

# Get my purchases
GET http://localhost:3333/api/purchases HTTP/1.1
Authorization: Bearer {{authTokenCoach}}

###