@hostname = localhost
@port = 3333
@host = http://{{hostname}}:{{port}}

@emailSportsman = user@notfound4.local
@emailCoach = user@notfound5.local
@password = 123456

@authToken = {{login.response.body.accessToken}}
# Login user by email and password
# @name login
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailCoach}}",
  "password": "{{password}}"
}

###

# Register a new sportsman 
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailSportsman}}",
  "dateBirth": "2020-12-23T12:45:00.000Z",
  "password": "{{password}}",
  "role": "user",
  "name": "Москва",
  "avatar": "http://localhost:3333/static/9d4ee38c-4229-49f3-a6be-26f9f7b87b58.png",
  "gender": "Мужской",
  "locationDefault": "ст. м. Пионерская",
  "exerciseLevel": "Новичок",
  "exerciseTypes": ["Аэробика"],
  "durationTraining": "10-30 мин",
  "caloriesResetCount": 3000,  
  "caloriesSpendPerDayCount": 3000,  
  "isReadyUser": true
}

###

# Register a new coach
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailCoach}}",
  "dateBirth": "2020-12-23T12:45:00.000Z",
  "password": "{{password}}",
  "role": "coach",
  "name": "Москва",
  "avatar": "http://localhost:3333/static/9d4ee38c-4229-49f3-a6be-26f9f7b87b58.png",
  "gender": "Мужской",
  "locationDefault": "ст. м. Пионерская",
  "exerciseLevel": "Новичок",
  "exerciseTypes": ["Аэробика"],
  "comment": "sdgssssssssssfdgfdgfd",
  "isReadyCoach": true,
  "certificate": "http://localhost:3333/static/5c797d72-ba8c-4e07-8646-f37803b0b563.pdf"
}

###



@refreshToken = {{login.response.body.refreshToken}}

# Refresh tokens
GET {{host}}/api/auth/refresh-token HTTP/1.1
Authorization: Bearer {{refreshToken}}

###

# Upload Avatar
POST {{host}}/api/files/avatar
Content-Type: multipart/form-data; boundary=Upload

--Upload
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< test-files-upload/photo-4.png
--Upload--

###


# Upload Certificate
POST {{host}}/api/files/certificate
Content-Type: multipart/form-data; boundary=Upload

--Upload
Content-Disposition: form-data; name="file"; filename="1.pdf"
Content-Type: application/pdf

< test-files-upload/_Vyalov_Berezhlivoye_proizvodstvo.pdf
--Upload--

###