@hostname = localhost
@port = 3333
@host = http://{{hostname}}:{{port}}

@emailSportsman = user@notfound2.local

@password = 123456

@authTokenSportsman = {{loginSportsman.response.body.accessToken}}

# Login sportsman1
# @name loginSportsman
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailSportsman}}",
  "password": "{{password}}"
}

###

# Get gyms
GET {{host}}/api/gyms HTTP/1.1
Authorization: Bearer {{authTokenSportsman}}

###