@hostname = localhost
@port = 3333
@host = http://{{hostname}}:{{port}}

@emailSportsman = user@notfound2.local
@emailCoach = user@notfound3.local
@password = 123456

@authTokenCoach = {{loginCoach.response.body.accessToken}}
@authTokenSportsman = {{loginSportsman.response.body.accessToken}}
# Login coach
# @name loginCoach
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailCoach}}",
  "password": "{{password}}"
}

###
# Login sportsman
# @name loginSportsman
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailSportsman}}",
  "password": "{{password}}"
}

###

# Add a new friend
POST {{host}}/api/friends HTTP/1.1
Authorization: Bearer {{authTokenSportsman}}
Content-Type: application/json

{
  "friendId": "e9ede6f8-6210-4dd2-9215-e8446663fa14"
}

###

# Get my friends
GET {{host}}/api/friends HTTP/1.1
Authorization: Bearer {{authTokenCoach}}

###