@hostname = localhost
@port = 3333
@host = http://{{hostname}}:{{port}}

@emailSportsman = user@notfound2.local
@emailCoach = user@notfound5.local
@password = 123456

@authTokenCoach = {{loginCoach.response.body.accessToken}}
@authTokenSportsman = {{loginSportsman.response.body.accessToken}}
# Login coach
# @name loginCoach
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailCoach}}",
  "password": "{{password}}"
}

###
# Login sportsman
# @name loginSportsman
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{emailSportsman}}",
  "password": "{{password}}"
}

###

# Create a new exercise 
# @name createExercise
POST {{host}}/api/exercises HTTP/1.1
Authorization: Bearer {{authTokenCoach}}
Content-Type: application/json

{
  "title": "title",
  "level": "Новичок",
  "type": "Йога",
  "duration": "больше 80 мин",
  "price": 1000,
  "caloriesCount": 1000,
  "description": "description",
  "gender": "для мужчин",
  "video": "string",
  "isSpecialOffer": true
}

###

@exerciseId = {{createExercise.response.body.$.id}}

# Get my exercises
GET {{host}}/api/exercises  HTTP/1.1
Authorization: Bearer {{authTokenCoach}}
###

# Get exercise by id
GET {{host}}/api/exercises/{{exerciseId}} HTTP/1.1
Authorization: Bearer {{authTokenSportsman}}

###

# Update exercise 
PATCH  http://localhost:3333/api/exercises/{{exerciseId}} HTTP/1.1
Authorization: Bearer {{authTokenCoach}}
Content-Type: application/json

{
  "title": "titletitle",
  "image": "string",
  "level": "Новичок",
  "type": "Йога",
  "duration": "10-30 мин",
  "description": "descriptiondescription"
}

###
