# Create a new exercise 
POST http://localhost:3333/api/exercises HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZWU3MzE0MC0wNWQxLTQxMTktYjU2My1lODRhZmQwNjk3ODAiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQyMC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsIm5hbWUiOiLQnNC-0YHQutCy0LAiLCJpYXQiOjE2ODA1NTY2NDMsImV4cCI6MTY4MDU1NzU0M30.CL2cuCtX3ihnVMThvz2f5zU1tqCA7iEC72CbiPRS8TA
Content-Type: application/json

{
  "title": "title",
  "level": "Новичок",
  "type": "Йога",
  "duration": "больше 80 мин",
  "price": 1000,
  "caloriesCount": 1000,
  "description": "description",
  "gender": "для мужчин",
  "video": "string",
  "isSpecialOffer": true
}

###

# Get my exercises
GET http://localhost:3333/api/exercises?limit=10&durations=30-50 мин,10-30 мин&priceRange=10-9999&calorieRange=10-9999 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZDAwMjk1Zi00NDE2LTQ1YjgtYTk5NC0xNmY5MDVjMTU0ZDUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQyMC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsIm5hbWUiOiLQnNC-0YHQutCy0LAiLCJpYXQiOjE2ODA0NTU5NTUsImV4cCI6MTY4MDQ1Njg1NX0.e8XbPwtiqyYyji1WGGV2jikS7qkV5ggy_BL-fL2b-20
###

# Get exercise by id
GET http://localhost:3333/api/exercises/887b6b07-c474-423b-9d3e-eb5a14b3aab5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZDAwMjk1Zi00NDE2LTQ1YjgtYTk5NC0xNmY5MDVjMTU0ZDUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQyMC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsIm5hbWUiOiLQnNC-0YHQutCy0LAiLCJpYXQiOjE2Nzk5Mjg5MjYsImV4cCI6MTY3OTkyOTgyNn0.zGFi-SOyaEc1WThhFhQ62otMS1w_xqON4FFy4bCWdHY

###

# Update exercise 
PATCH  http://localhost:3333/api/exercises/887b6b07-c474-423b-9d3e-eb5a14b3aab5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZDAwMjk1Zi00NDE2LTQ1YjgtYTk5NC0xNmY5MDVjMTU0ZDUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQyMC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsIm5hbWUiOiLQnNC-0YHQutCy0LAiLCJpYXQiOjE2Nzk5Mjg5MjYsImV4cCI6MTY3OTkyOTgyNn0.zGFi-SOyaEc1WThhFhQ62otMS1w_xqON4FFy4bCWdHY
Content-Type: application/json

{
  "title": "titletitle",
  "image": "string",
  "level": "Новичок",
  "type": "Йога",
  "duration": "10-30 мин",
  "description": "descriptiondescription"
}

###
